# Use root/example as user/password credentials
version: '3.7'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  node-app:
    build: .
    image: node-app:1.0
    ports:
      - 9999:9999